[book]
authors = ["Syfaro", "gedjerone"]
language = "en"
multilingual = false
src = "docs"
title = "Go Telegram Bot API"

[output.html]
git-repository-url = "https://github.com/gedjerone/telegram-bot-api"
